; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Українізатор для Caesar IV"
#define MyAppVersion "1.2"
#define MyAppPublisher "romamakar"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{70EF7C9D-66EF-4B99-9199-BF6A477BA304}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf32}\Steam\steamapps\common\Caesar 4\C4
DisableDirPage=no
;DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=Caesar4_Ukr_Installer
OutputDir=Output
SetupIconFile=D:\a\Caesar4Ukr\Caesar4Ukr\installer\installer.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Files]
Source: "D:\a\Caesar4Ukr\Caesar4Ukr\output\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename:"{app}\CaesarIV.exe"; Description:"Запустити Caesar 4"; Flags: postinstall nowait shellexec

